### ISSUE TITLE
[Issue]Mismatch CRCs with Nkit 1.4

### ISSUE THREAD

**Issue by Immersion95** [Nanook/NKitv1#4]
Hi,

For some known verified nkit.gcz dumps, the CRC fails to match when I try "Recover to ISO", though it succeeds when I "Convert to ISO".

Example : Mario Party 4, 5 & 7 (USA)

Verified nkit.gcz ---->Recover to ISO---->Match failed
Verified nkit.gcz ---->Convert to ISO---->Match verified

Is it just me ? Can somebody else try ?

Thanks !

**Comment by Nanook** [comment]
Recover to ISO will only work on GC if you have the Recovery files. It will not work with Wii as it can not reposition the files.

**Comment by Immersion95** [comment]
Hi,

I already have all the recovery files though.

Can you please test and confirm that the problem comes from me ?

Thanks.
